export const FEATURE_KEYS = {
  CORE_PROCUREMENT: "CORE_PROCUREMENT",
  SUPPLIER_MANAGEMENT: "SUPPLIER_MANAGEMENT",
  SUPPLIER_PORTAL: "SUPPLIER_PORTAL",
  STRATEGIC_SOURCING: "STRATEGIC_SOURCING",
  CONTRACT_MANAGEMENT: "CONTRACT_MANAGEMENT",
  INVENTORY: "INVENTORY",
  LOGISTICS: "LOGISTICS",
  CATEGORY_MANAGEMENT: "CATEGORY_MANAGEMENT",
  SUSTAINABLE_PROCUREMENT: "SUSTAINABLE_PROCUREMENT",
  API_ACCESS: "API_ACCESS",
  SSO: "SSO",
  ERP_CONNECTORS: "ERP_CONNECTORS",
  WORKFLOW_STUDIO: "WORKFLOW_STUDIO",
  REPORT_BUILDER: "REPORT_BUILDER",
  MOBILE: "MOBILE",
  AI_PLATFORM: "AI_PLATFORM",
} as const;

export type FeatureKey =
  (typeof FEATURE_KEYS)[keyof typeof FEATURE_KEYS];

export type FeatureAccessDecision = {
  allowed: boolean;
  source:
    | "TENANT_ALLOW"
    | "TENANT_DENY"
    | "EDITION"
    | "MANAGED_PAAS_ONLY"
    | "NO_SUBSCRIPTION"
    | "UNKNOWN_FEATURE";
  featureKey: string;
  editionCode?: string;
};
